/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mayormenorventanas;

/**
 *
 * @author Admin
 */
public class MiPantalla extends javax.swing.JFrame {
int n_aleatorio=0;
    /**
     * Creates new form MiPantalla
     */
    public MiPantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmpezar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroUsuario = new javax.swing.JTextField();
        btnComprobar = new javax.swing.JButton();
        lblRespuestaUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEmpezar.setText("Empezar juego");
        btnEmpezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpezarMouseClicked(evt);
            }
        });

        jLabel1.setText("Introduzca un número:");

        txtNumeroUsuario.setEnabled(false);

        btnComprobar.setText("Probar");
        btnComprobar.setActionCommand("Probar");
        btnComprobar.setEnabled(false);
        btnComprobar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprobarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnEmpezar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnComprobar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblRespuestaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnEmpezar)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprobar))
                .addGap(38, 38, 38)
                .addComponent(lblRespuestaUsuario)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpezarMouseClicked
        // TODO add your handling code here:
        
        //Pensar un número aleatorio
        n_aleatorio=(int)(Math.random()*9);
        //Habilitar el textfield
        txtNumeroUsuario.setEnabled(true);
        //Habiitar el botón de pprobar
        btnComprobar.setEnabled(true);
        //Deshabilitar el botón de empezar a jugar
        btnEmpezar.setEnabled(false);
        
    }//GEN-LAST:event_btnEmpezarMouseClicked

    private void btnComprobarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprobarMouseClicked
        // TODO add your handling code here:
        //1-Ver qué numero ha escrito el usuario
        String n_usuario=txtNumeroUsuario.getText();
        
        int n_usuario_int=Integer.parseInt(n_usuario);
        //2-Comparar el numero aleatorio con el que escribió el usuario
        String respuesta="";
        if(n_aleatorio==n_usuario_int)
        {
            respuesta="Enhorabuena";
            btnEmpezar.setText("Volver a jugar");
            btnEmpezar.setEnabled(true);
            txtNumeroUsuario.setEnabled(false);
            btnComprobar.setEnabled(false);
        }else if(n_aleatorio<n_usuario_int)
        {
            //El numero pensado es menor
            respuesta="El número pensado es menor";
            
        }else
        {
            //El numero pensado es mayor
            respuesta="El número pensado es mayor";
           
        }
        lblRespuestaUsuario.setText(respuesta);
       
        
    }//GEN-LAST:event_btnComprobarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiPantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobar;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblRespuestaUsuario;
    private javax.swing.JTextField txtNumeroUsuario;
    // End of variables declaration//GEN-END:variables
}
